gfont: 
    - "Montserrat:700"
    - "Open+Sans:400,400italic,700,700italic"

images:
    - "slanted/images/death-to-stock-dinner-damo-7.jpg" 
    - "slanted/images/death-to-stock-dinner-damo-3.jpg" 
    - "slanted/images/death-to-stock-dinner-damo-4.jpg"
